### PR TITLE
Object manipulation

### PR DESCRIPTION
**Pull request by joshuajhun**
This is a problem we've given our students. It's supposed to push them to get better at object manipulation. Included in this PR is a test suite and my implementation of the solution. If you'd like to see the end goal I suggest looking at this [test](https://github.com/joshuajhun/tdd/compare/object-manipulation?expand=1#diff-9f580830298a9380c34fbeb284125162R114) to get an idea of what needs to happen. @acareaga && @adamki I would love your feedback!

### CODE REVIEW

**Comment by adamki** [comment]
AYYYYYYYYYYYEEEEEEEEEEEEEEEEEEE!

looks cool so far! I wish i could do `{suh: 'dude'}` at my job!

Here are some ideas I had while _perusing_ through this PR: 
* a test that it `should not mutate the original object`. I thought this might be valuable since we see this pattern in libs like redux and mobx so much.
* a test that it `should handle different key types`. ugh... thats a terrible test name... but something I noticed was that all the tests were so kind. [this line](https://github.com/joshuajhun/tdd/compare/object-manipulation?expand=1#diff-9f580830298a9380c34fbeb284125162R115) only has values that are numbers. A test that asks students to handle types/type checking might be helpful.
* kind of grasping at straws here... but if you want... you could ask them to do a couple of problems without fancy fancy stuff like `Object.keys` or `Object.assign`. But then it kind of turns into a lesson on loops and reduce and stuff. totes up to you

**Comment by joshuajhun** [comment]
Thanks for the feedback @adamki. What test are you talking about where I’m manipulate the original object?

**Comment by joshuajhun** [comment]
Also they are pretty terrible test names 😅😅😅

**Comment by joshuajhun** [comment]
I totally misread your suggestion. I’ll def write a test like that!! @adamki

**Pull request closed without merging**
